version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
    environment:
      DB_URL: mongodb://mongo/test?retryWrites=true&w=majority
  mongo:
    image: mongo
    ports:
      - "27017:27017"
